apiVersion: v1
kind: Service
metadata:
  name: product-server
spec:
  selector:
    app: product-server
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081

---
# To test prod server connection from outside the cluster

apiVersion: v1
kind: Service
metadata:
  name: product-server-nodeport
spec:
  selector:
     app: product-server
  ports:
    - nodePort: 30002
      port: 8081    
      targetPort: 8081
  type: NodePort