apiVersion: v1
kind: Service
metadata:
  name: product-web
spec:
  selector:
    app: product-web
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  #clusterIP: 10.96.1.10
  type: LoadBalancer