apiVersion: skaffold/v1beta4
kind: Config
build:
  local:
    push: false
  artifacts:
    - image: santonix/spring-boot-docker-k8s-helm
      # jibGradle: {}
      jibMaven: {}
deploy:
  kubectl:
    manifests:
      - k8s/*.yml
