version: "3"

services:

  db:
    image: mongo:5.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - "db-data:/data/db"
    networks:
      - santonix-network
   
  server:
    build: ./01-ProductServer
    # image: santonix/product-server
    container_name: product-server
    ports:
      - "8081:8081"
    depends_on:
      - "db"
    networks:
      - santonix-network
    environment:
      - spring.data.mongodb.uri=mongodb://mongo:27017/test

  web:
    build: ./02-ProductWeb
    # image: santonix/product-web
    container_name: product-web
    depends_on:
      - "server"
    ports:
      - "8080:8080"
    networks:
      - santonix-network
    environment:
      - acme.PRODUCT_SERVICE_URL=http://product-server:8081/products
    
    
volumes:
  db-data:
      driver: local
      driver_opts:
         o: bind
         type: none
         #device: mongodata
         device: /home/bonny/mongodata

networks:
   santonix-network:
 
