apiVersion: v1
kind: Pod
metadata:
  name: load-test
spec:
  containers:
  - name: load-test
    image: curlimages/curl:8.10.1  # lightweight curl container
    command: ["/bin/sh", "-c"]
    args:
      - |
        i=0
        while true; do
          curl -s http://product-web:8080/productsweb
          echo ""
          echo "------------------------------------------"
          echo "Current date: $(date)"
          echo "=========================================="
          sleep 2
          i=$((i+1))
          echo "Firing http://product-web:8080/productsweb $i time and waiting..."
          echo ""
        done
