
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-data-db
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    #path: "/Users/binil/dockerbook/ch08-05/mongodata"
    path: "/home/docker/mongodata"







