

# To restrict access of mongo within the cluster, use type: ClusteredIP (default)

apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  selector:
    app: mongo
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  
---

# To test mongo connection from outside the cluster, use type: NodePort
apiVersion: v1
kind: Service
metadata:
  name: mongo-nodeport
spec:
  selector:
     app: mongo
  ports:
    - nodePort: 30001
      port: 27017    
      targetPort: 27017
  type: NodePort