apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-server
  labels:
    app: product-server
    group: backend
spec:
  #replicas: 1
  replicas: 3
  selector:
    matchLabels:
      app: product-server
  template:
    metadata:
      labels:
        app: product-server
    spec:
      containers:
      - name: product-server
        image: santonix/product-server
        ports:
        - containerPort: 8081
        imagePullPolicy: Always
        env:
          - name: spring.data.mongodb.uri
            value: mongodb://mongo:27017/test
          - name: spring.kafka.bootstrap-servers
            value: kafka-1-ip-service:9092